# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGE_PRODUCT, ROLE_MANAGE_CATEGORY, ROLE_MANAGE_USER, ROLE_BROWSE_CATALOG, ROLE_ALLOWED_TO_SWITCH]
        ROLE_MOD: [ROLE_MANAGE_PRODUCT, ROLE_MANAGE_CATEGORY, ROLE_BROWSE_CATALOG]
        ROLE_USER: [ROLE_BROWSE_CATALOG]
    encoders:
        AppBundle\Entity\User: bcrypt
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_users:
            entity: { class: AppBundle\Entity\User, property: email }
        in_memory:
            memory:
                users:
                    dima:
                        password: 123
                        roles: 'ROLE_ADMIN'
                    dimon:
                        password: 1
                        roles: 'ROLE_USER'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            logout:
                path: /logout
            switch_user: true